import { useEffect, useMemo, useRef, useState } from 'react';
import { observer } from 'mobx-react-lite';
import { FrameworkProvider } from 'fumadocs-core/framework';
import { RootProvider } from 'fumadocs-ui/provider/base';
import { DocsLayout } from 'fumadocs-ui/layouts/docs';
import { DocSourceStore } from './store/DocSourceStore.js';
import { DocStore } from './store/DocStore.js';
import { CompStateStore } from './store/CompStateStore.js';
import { StoreContext, useDocStores } from './store/context.js';
import { makeFramework } from './lib/framework-adapter.jsx';
import { DocPageView } from './DocPageView.jsx';
import { DocSearchDialog } from './comp-doc/DocSearchDialog.jsx';
import { compById as compByIdDefault } from './comp-doc/registry.js';

// Embeddable MD/MDX document page.
//
//   <DocPageMdx
//     data={{ configDoc, fileManifest }}
//     config={{ routeMode: 'memory', compById, link: { CompRender } }}
//     onEvent={(eventType, eventData) => { ... }}
//   />
//
// data usually comes from the virtual module generated by docSourcePlugin().
// config contains application/runtime policy rather than semantic document data.

export function DocPageMdx({ data, config = {}, onEvent }) {
  const pageElementRef = useRef(null);
  const [stores] = useState(() => {
    const compById = { ...compByIdDefault, ...(config.compById ?? {}) };
    const sourceStore = new DocSourceStore(data, {
      compile: config.compile,
      linkResolve: config.link?.resolve,
    });
    const docStore = new DocStore(sourceStore, {
      routeMode: config.routeMode ?? 'memory',
      compById,
    });
    const compStateStore = new CompStateStore();
    return { sourceStore, docStore, compStateStore, compById };
  });
  const framework = useMemo(() => makeFramework(stores.docStore), [stores]);
  const contextValue = useMemo(() => ({
    ...stores,
    linkConfig: config.link ?? {},
    onEvent,
    pageElementRef,
  }), [stores, config.link, onEvent]);

  useEffect(() => {
    stores.docStore.init();
    return () => stores.docStore.dispose();
  }, [stores]);

  useEffect(() => {
    if (typeof data.subscribe !== 'function') return undefined;
    return data.subscribe((sourceDataNext) => stores.docStore.replaceSourceData(sourceDataNext));
  }, [data, stores]);

  return (
    <div ref={pageElementRef} className="doc-page-mdx">
      <StoreContext.Provider value={contextValue}>
        <FrameworkProvider {...framework}>
          <RootProvider search={{ SearchDialog: DocSearchDialog }}>
            <DocsShell />
          </RootProvider>
        </FrameworkProvider>
      </StoreContext.Provider>
    </div>
  );
}

const DocsShell = observer(function DocsShell() {
  const { docStore, sourceStore } = useDocStores();
  return (
    <DocsLayout
      tree={docStore.treePage}
      nav={{ title: sourceStore.configDoc.siteTitle ?? 'Docs' }}
    >
      <DocPageView />
    </DocsLayout>
  );
});
