import { useEffect, useMemo, useRef, useState } from 'react';
import { observer } from 'mobx-react-lite';
import { DocsLayout, DocsLayoutContainer, FrameworkProvider, RootProvider, ThemeSwitch } from '../UICommon.js';
import { DocSourceStore } from './store/DocSourceStore.js';
import { DocStore } from './store/DocStore.js';
import { DocConfigStore } from './store/DocConfigStore.js';
import { DocTagStore } from './store/DocTagStore.js';
import { CompStateStore } from './store/CompStateStore.js';
import { StoreContext, useDocStores } from './store/context.js';
import { makeFramework } from './lib/framework-adapter.jsx';
import { DocPageView } from './DocPageView.jsx';
import { DocNavigationButtons } from '../../comp-doc/page/DocNavigationButtons.jsx';
import { DocSearchDialog } from '../../comp-doc/page/DocSearchDialog.jsx';
import { DocSidebarFolder } from '../../comp-doc/side-panel/DocSidebarFolder.jsx';
import { TagOverviewPopup } from '../../comp-doc/tag/TagOverviewPopup.jsx';
import { DocLanguageProvider, useDocLanguage } from '../../comp-mdx/multi-lang/MultiLangContext.jsx';
import { MultiLangControl } from '../../comp-mdx/multi-lang/MultiLangControl.jsx';
import { compById as compByIdDefault } from '../../comp-doc/registry/registry.js';
import './DocPageMdx.css';

// Embeddable MD/MDX document page.
//
//   <DocPageMdx
//     data={{ configDoc, fileManifest }}
//     config={{ routeMode: 'memory', compById, compConfigHost, configDefineList, link: { CompRender } }}
//     onEvent={(eventType, eventData) => { ... }}
//   />
//
// data usually comes from the virtual module generated by docSourcePlugin().
// config contains application/runtime policy rather than semantic document data.

export function DocPageMdx({ data, config = {}, onEvent }) {
  const languageAncestor = useDocLanguage();
  const languagePage = config.language || languageAncestor;
  const pageElementRef = useRef(null);
  const headingPointerRef = useRef(null);
  const [stores] = useState(() => {
    const compById = { ...compByIdDefault, ...(config.compById ?? {}) };
    const sourceStore = new DocSourceStore(data, {
      compile: config.compile,
      linkResolve: config.link?.resolve,
    });
    const docStore = new DocStore(sourceStore, {
      routeMode: config.routeMode ?? 'memory',
      compById,
      language: languagePage,
      onInvalidBrowserRoute: config.onInvalidBrowserRoute,
    });
    const configStore = new DocConfigStore(sourceStore, docStore, {
      configDefineList: config.configDefineList,
    });
    const tagStore = new DocTagStore(sourceStore, docStore, configStore);
    const compStateStore = new CompStateStore();
    return { sourceStore, docStore, configStore, tagStore, compStateStore, compById };
  });
  const framework = useMemo(() => makeFramework(stores.docStore), [stores]);
  const contextValue = useMemo(() => ({
    ...stores,
    compConfigHost: config.compConfigHost ?? {},
    componentConfig: config.components ?? {},
    linkConfig: config.link ?? {},
    onEvent,
    pageElementRef,
    sidePanelConfig: config.sidePanel ?? {},
  }), [stores, config.compConfigHost, config.components, config.link, config.sidePanel, onEvent]);

  useEffect(() => {
    stores.docStore.init();
    return () => stores.docStore.dispose();
  }, [stores]);

  useEffect(() => {
    stores.docStore.replaceCompById({
      ...compByIdDefault,
      ...(config.compById ?? {}),
    });
  }, [config.compById, stores]);

  useEffect(() => {
    stores.docStore.setLanguagePage(languagePage);
  }, [languagePage, stores]);

  useEffect(() => {
    if (typeof data.subscribe !== 'function') return undefined;
    return data.subscribe((sourceDataNext) => stores.docStore.replaceSourceData(sourceDataNext));
  }, [data, stores]);

  return (
    <div
      ref={pageElementRef}
      className="doc-page-mdx"
      onClickCapture={(event) => {
        const headingAnchor = headingAnchorGet(event.target);
        const pointer = headingPointerRef.current;
        const selection = typeof window === 'undefined' ? null : window.getSelection();
        const isTextSelected = Boolean(selection && !selection.isCollapsed && selection.toString());
        const isDragged = Boolean(
          headingAnchor
          && pointer?.headingAnchor === headingAnchor
          && Math.hypot(pointer.xEnd - pointer.xStart, pointer.yEnd - pointer.yStart) > 5
        );
        headingPointerRef.current = null;
        if (!headingAnchor || (!isTextSelected && !isDragged)) return;
        event.preventDefault();
        event.stopPropagation();
      }}
      onPointerDownCapture={(event) => {
        if (event.button !== 0) return;
        const headingAnchor = headingAnchorGet(event.target);
        headingPointerRef.current = headingAnchor
          ? {
              headingAnchor,
              pointerId: event.pointerId,
              xEnd: event.clientX,
              xStart: event.clientX,
              yEnd: event.clientY,
              yStart: event.clientY,
            }
          : null;
      }}
      onPointerMoveCapture={(event) => {
        const pointer = headingPointerRef.current;
        if (!pointer || pointer.pointerId !== event.pointerId) return;
        pointer.xEnd = event.clientX;
        pointer.yEnd = event.clientY;
      }}
      onPointerUpCapture={(event) => {
        const pointer = headingPointerRef.current;
        if (!pointer || pointer.pointerId !== event.pointerId) return;
        pointer.xEnd = event.clientX;
        pointer.yEnd = event.clientY;
      }}
      onPointerCancelCapture={() => { headingPointerRef.current = null; }}
    >
      <DocLanguageProvider language={languagePage}>
        <StoreContext.Provider value={contextValue}>
          <FrameworkProvider {...framework}>
            <RootProvider search={{ SearchDialog: DocSearchDialog }}>
              <DocsShell />
              <TagOverviewPopup />
            </RootProvider>
          </FrameworkProvider>
        </StoreContext.Provider>
      </DocLanguageProvider>
    </div>
  );
}

function headingAnchorGet(target) {
  if (!(target instanceof Element)) return null;
  const anchor = target.closest('a[href^="#"]');
  if (!anchor || !/^H[1-6]$/.test(anchor.parentElement?.tagName ?? '')) return null;
  return anchor;
}

const DocsShell = observer(function DocsShell() {
  const { docStore, sidePanelConfig, sourceStore } = useDocStores();
  const sidePanelProps = useMemo(() => ({
    ...sidePanelConfig,
    components: {
      Folder: DocSidebarFolder,
      ...(sidePanelConfig.components ?? {}),
    },
  }), [sidePanelConfig]);
  return (
    <DocsLayout
      tree={docStore.treePage}
      nav={{ title: sourceStore.configDoc.siteTitle ?? 'Docs' }}
      sidebar={sidePanelProps}
      slots={docsLayoutSlots}
      themeSwitch={themeSwitchSidebarDisabled}
    >
      <DocPageView />
    </DocsLayout>
  );
});

const docsLayoutSlots = { container: DocPageLayoutContainer };

// the sidebar-footer theme toggle can end up below the window's bottom edge
// when the side panel is tall; the floating toggle below replaces it.
const themeSwitchSidebarDisabled = { enabled: false };

function DocPageLayoutContainer({ children, ...props }) {
  return (
    <DocsLayoutContainer {...props}>
      {children}
      <div className="doc-theme-floating">
        <ThemeSwitch />
      </div>
      <nav className="doc-navigation-floating" aria-label="Document navigation and language">
        <DocNavigationButtons isCompact />
        <MultiLangControl />
      </nav>
    </DocsLayoutContainer>
  );
}
